name: victor_flutter
description: This project was made to test my knowledge.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.1.4
  dio:
  skeletons:
  splashscreen:
  shared_preferences:
  cached_network_image:
  flutter_svg:
  dartz:
  connectivity:
  overlay_support:





  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:


flutter:

  uses-material-design: true

  assets:
    - assets/img/

